services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=main_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:latest
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=test_database

  back_cogna:
    image: back-end:local
    ports:
      - '3333:3333' 
    environment:
      - NODE_ENV=production
      - PORT=3333
      - JWT_SECRET=asdasdasd
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/main_database
    command: ["sh", "-c", "pnpm run generate && node dist/server.js"]
    depends_on:
      - postgres
    restart: on-failure

  front_cogna:
    image: front-end:local
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_API_URL=http://back_cogna:3333
    depends_on:
      - back_cogna
    restart: on-failure

volumes:
  postgres_data: