apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-cogna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-cogna
  template:
    metadata:
      labels:
        app: back-cogna
    spec:
      initContainers:
        - name: wait-for-postgres
          image: alpine
          command:
            - sh
            - -c
            - |
              apk add --no-cache netcat-openbsd && \
              until nc -z postgres 5432; do echo "⏳ Esperando o PostgreSQL subir..."; sleep 2; done
      containers:
        - name: back-cogna
          image: back-end:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3333
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              value: "postgresql://docker:docker@postgres:5432/main_database"
            - name: JWT_SECRET
              value: "eyJhbGciOiJIUzI1NiJ9..."
            - name: PORT
              value: "3333"
            - name: FRONT_END_URL
              value: "http://front-cogna"
          command: ["sh", "-c", "pnpm run generate && node dist/server.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: back-cogna
spec:
  selector:
    app: back-cogna
  ports:
    - port: 3333
      targetPort: 3333
  type: LoadBalancer